### ISSUE TITLE
what timezone should LoggingMetrics use for timestamps?

### ISSUE THREAD

**Issue by willkg** [willkg/markus#11]
What timezone should LoggingMetrics use for timestamps? Why?

Should it be configurable? Why?

What does the Python logging module do for timestamps and timezones?

**Comment by peterbe** [comment]
How about *always* UTC and use a format that includes the timezone. E.g.

```python
>>> import datetime
>>> datetime.datetime.utcnow().astimezone().isoformat()
'2018-04-20T11:24:56.645570-04:00'
```

Then you don't have to worry so much about the timezone since it's in the string already and it's same for everyone.

**Comment by peterbe** [comment]
I *think* to get this to work in Python 2, you need to depend on https://pypi.python.org/pypi/pytz/ :(

**Comment by willkg** [comment]
I'm going to add a mode:

1. no timestamp
2. native timezone timestamp
3. utc timestamp

and have it default to no timestamp because it's likely that logging is configured to include a timestamp already.
