### ISSUE TITLE
add a statsd backend

### ISSUE THREAD

**Issue by willkg** [willkg/markus#3]
We have a datadog backend, but we should also add a regular statsd backend.

**Comment by willkg** [comment]
https://pypi.python.org/pypi/statsd

**Comment by jruere** [comment]
TCPStatsClient is not thread-safe. Should it be supported?

**Comment by jruere** [comment]
Also, it appears that pystatsd does not support tags. Should they be ignored?

**Comment by willkg** [comment]
I think it's a good idea for Markus to be thread-safe. That's probably something we should mention in the README. I suspect it is, but we'd want to go through and make sure it is.

I bet someone could write a backend for TCPStatsClient that's thread-safe, but I don't think that's something I'm going to do. Alternatively, maybe it's worth fixing the pystatsd library so that the TCPStatsClient is thread-safe.

If the backend doesn't support tags directly, then maybe see if there's another way to "implement tags" and if not, maybe ignore them. It's definitely worth adding a note to the class docstring if they're ignored or if they're implemented in an unusual manner.

For example:

https://github.com/willkg/markus/blob/fe2d5a365beb2a4dfa650c1790332c03ee14c376/markus/backends/cloudwatch.py#L31

Does that answer your questions? Is this something you want to work on?

**Comment by jruere** [comment]
I agree on the value of being thread-safe. It should really be in the README since it could be hard to assess. Maybe per backend?

I don't understand what tags are in DataDog, which I suppose is the API this library implements. Nevertheless, vanilla statsd does not support them so I guess it should be ignored.

Thanks for the answers. I'll implement StatsD over UDP using the statsd module ignoring tags and implementing histogram with timing.

**Comment by willkg** [comment]
Tags for Markus are documented here:

http://markus.readthedocs.io/en/latest/metricsoverview.html#using-tags

They're used in the Datadog statsd backend and the logging backend. At some point, I'll add them to the logging rollup backend, but I have to think about how that works first.

Tags in Datadog's statsd are documented here:

http://docs.datadoghq.com/guides/dogstatsd/#tags

I think your plan sounds great! Thank you!

**Comment by jruere** [comment]
Lets continue the conversation about tags in #21.

I created PR #20 for the discussed implementation.

**Comment by willkg** [comment]
Pretty sure pull #22 implemented the statsd backend and we're all good here. Closing this out.
