### ISSUE TITLE
Enable pytest asserts for MetricsMock helpers

### ISSUE THREAD

**Issue by jwhitlock** [willkg/markus#73]
When using ``MetricsMock`` for testing (https://github.com/mozilla/ichnaea/pull/1164#discussion_r421811737), methods like ``assert_incr_once`` use plain assertions, rather than pytest rewritten assertions, such as:

```
Traceback (most recent call last):
  File "/app/ichnaea/content/tests/test_views.py", line 112, in test_content
    metricsmock.assert_incr_once('request', tags=[f"path:{metric_path}", "method:get", f"status:{status}"])
  File "/usr/local/lib/python3.8/site-packages/markus/testing.py", line 106, in assert_incr_once
    assert len(self.filter_records(INCR, stat=stat, value=value, tags=tags)) == 1
AssertionError
```

I enabled assertion rewriting in my project's ``conftest.py`` file:

```python
pytest.register_assert_rewrite("markus.testing")
from markus.testing import MetricsMock  # noqa: E402
```

A similar method could be used in ``markus.__init__.py``, according to [pytest assertion rewriting docs](https://docs.pytest.org/en/latest/writing_plugins.html#assertion-rewriting). Something like:

```python
try:
   import pytest
except ImportError:
   pass
else:
   pytest.register_assert_rewrite("markus.testing")
```

**Comment by willkg** [comment]
@jwhitlock Thank you!
