### ISSUE TITLE
pytest import in `__init__.py` makes it difficult to determine when pytest is running

### ISSUE THREAD

**Issue by jwhitlock** [willkg/markus#95]
For https://github.com/mozilla/fx-private-relay/pull/1809, I wanted to enable code only if we're not running pytest. There's [one way to do it](https://pytest.org/en/6.2.x/example/simple.html#detect-if-running-from-within-a-pytest-run), and a quick way (``if "pytest" in sys.modules``). Because markus imports pytest early (added for https://github.com/willkg/markus/issues/73), the quick method doesn't work.

I think I can make this work by adding a pytest plugin.

**Comment by willkg** [comment]
Fixed by #96.
